version: 2

jobs:
    build:
        working_directory: ~/pdf-generator
        docker:
            - image: openjdk:8
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Install sbt into build container
                command: |
                    apt-get update
                    apt-get install apt-transport-https
                    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
                    echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
                    apt-get update
                    apt-get install sbt
            - run:
                name: Run sbt build
                command: sbt assembly
